server:
  port: 8089


logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    com.tcloudata: debug
  path: ./runlog
  file: boot-table.log

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/boot_table?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    content-type: text/html
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  typeAliasesPackage: com.tcloudata.**.domain
#配置缓存和session存储方式，默认ehcache,可选redis
cacheType: ehcache

